# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"*\n\x0cInputMessage\x12\x11\n\x04\x64\x61ta\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_data\"G\n\rMappedMessage\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_value\"\'\n\x07Success\x12\x12\n\x05value\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value25\n\x0fMapProcessInput\x12\"\n\x07receive\x12\r.InputMessage\x1a\x08.Success29\n\x12ReduceProcessInput\x12#\n\x07receive\x12\x0e.MappedMessage\x1a\x08.Successb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTMESSAGE._serialized_start=18
  _INPUTMESSAGE._serialized_end=60
  _MAPPEDMESSAGE._serialized_start=62
  _MAPPEDMESSAGE._serialized_end=133
  _SUCCESS._serialized_start=135
  _SUCCESS._serialized_end=174
  _MAPPROCESSINPUT._serialized_start=176
  _MAPPROCESSINPUT._serialized_end=229
  _REDUCEPROCESSINPUT._serialized_start=231
  _REDUCEPROCESSINPUT._serialized_end=288
# @@protoc_insertion_point(module_scope)
